runtime: python37

entrypoint: gunicorn -b :$PORT wc:app

handlers:
  - url: /static
    static_dir: app/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  WC_ENVIRONMENT: 'dev'
